namespace ADOps.Core.Enums;

/// <summary>
/// Represents the validation state of an AI-generated investigation finding.
/// </summary>
public enum FindingStatus
{
    /// <summary>
    /// Finding generated by AI and awaiting human validation.
    /// </summary>
    Proposed,

    /// <summary>
    /// Finding reviewed and accepted as valid.
    /// </summary>
    Confirmed,

    /// <summary>
    /// Finding reviewed and rejected as invalid or unsupported.
    /// </summary>
    Rejected
}