namespace ADOps.Infrastructure.Knowledge;

/// <summary>
/// Coordinates Microsoft Learn document ingestion, chunking,
/// and replacement in the knowledge index.
/// </summary>
public sealed class MicrosoftLearnKnowledgeIndexingService
{
    private readonly MicrosoftLearnDocumentIngestionService
        _ingestionService;

    private readonly MicrosoftLearnDocumentChunker _chunker;

    private readonly InMemoryKnowledgeChunkIndex _index;

    public MicrosoftLearnKnowledgeIndexingService(
        MicrosoftLearnDocumentIngestionService ingestionService,
        MicrosoftLearnDocumentChunker chunker,
        InMemoryKnowledgeChunkIndex index)
    {
        _ingestionService = ingestionService
            ?? throw new ArgumentNullException(
                nameof(ingestionService));

        _chunker = chunker
            ?? throw new ArgumentNullException(
                nameof(chunker));

        _index = index
            ?? throw new ArgumentNullException(
                nameof(index));
    }

    /// <summary>
    /// Ingests a Microsoft Learn document and replaces its indexed
    /// chunks only after ingestion and chunking have completed.
    /// </summary>
    public async Task IndexAsync(
        Uri sourceUri,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(sourceUri);

        // Fetch and extract the complete document.
        var document = await _ingestionService.IngestAsync(
            sourceUri,
            cancellationToken);

        // Build all replacement chunks before modifying the index.
        var chunks = _chunker.Chunk(document);

        // Do not commit the update if cancellation was requested
        // while processing the document.
        cancellationToken.ThrowIfCancellationRequested();

        // Replace the document's indexed content in one operation.
        // Use the same source ID generated by the chunker.
        _index.ReplaceSource(
            document.SourceUri.AbsoluteUri,
            chunks);
    }
}